version: 0.0
os: linux
files:
  - source: /
    destination: /var/www/apps/hello-world
hooks:
  BeforeInstall:
    - location: scripts/BeforeInstall.sh
      
  AfterInstall:
    - location: scripts/AfterInstall.sh
      
  ApplicationStart:
    - location: scripts/ApplicationStart.sh
      


