version: 0.2

env:
  git-credential-helper: yes
  
phases:
  install:
    runtime-versions:
      ruby: 2.7
      nodejs: 12
    commands:
      - apt update
      - rbenv install 2.7.0
      - rbenv global 2.7.0
      - gem install bundler:1.10.6
      - apt install make
      - apt install -y gcc
      - chmod a+rwx Gemfile.lock
      - bundle install
  pre_build:
    commands:
      - git submodules update --init --recursive
artifacts:
  files:
    - '**/*'
  name: hello-world-build
